### PR TITLE
suggestions for IMHO better text

### PR DESCRIPTION
**Pull request by espinielli**
* moved "emphasis mine" before the quoted text because it read strange otherwise.
* added IMHO a missing "a"
* avoided repetition of too many "figure" in a couple of contiguous sentences

HTH

### CODE REVIEW

**Comment by clauswilke** [comment]
I can't merge this without a clear copyright assignment in the commit message. See here: https://serialmentor.com/dataviz/ (bottom of the page)

Also, there shouldn't be a space between `(emphasis mine)` and `:`.

**Comment by espinielli** [comment]
Ooops, yes no space.
Here is the copyright statement.

I assign the copyright of this contribution to Claus O. Wilke

**Comment by espinielli** [comment]
reworded commit message

**Comment by clauswilke** [comment]
Thanks, fixed on my end.

**Pull request closed without merging**
