### PR TITLE
typos in visualizing_uncertainty.Rmd

### PR DESCRIPTION
**Pull request by tjmahr**
fixed typos of "trial", "deterministic", "minimize"
moved a comma to after an "e.g."
changed an "e.g." to an "i.e."

I assign the copyright of this contribution to Claus O. Wilke.

### CODE REVIEW

**Comment by clauswilke** [comment]
Thanks! Would you mind amending your commit comment to include "I assign the copyright of this contribution to Claus O. Wilke", as described [here?](https://serialmentor.com/dataviz/) I try to be consistent about this, even if we're talking about fixes for minor typos.

**Comment by tjmahr** [comment]
Done. Thanks to this guide https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages

**Comment by clauswilke** [comment]
Thanks. Do you use RStudio git integration? It has a convenient "amend previous commit" button. (And generally works great, except when it crashes RStudio once every 20 commits or so...)

**Comment by tjmahr** [comment]
I made my original edits through GitHub so I assumed I had to use fancier command-line stuff to fix a message that already was in a pull request on GitHub. But yeah, 95% of my git work is through the RStudio integration 😄 

By the way, glad to see you getting mileage from the chocolate ratings dataset!

**Pull request merged**
