### PR TITLE
add non-negative labels to age pyramid

### PR DESCRIPTION
**Pull request by malcolmbarrett**
I tweaked the age pyramid to have non-negative labels for males. If you don't think that's a good idea, you can always just stamp_bad() it ;)

### CODE REVIEW

**Comment by malcolmbarrett** [comment]
Oops, sorry, I forgot to include this copyright thing on this one, too. I assign the copyright of this contribution to Claus O. Wilke. If I see anything else, I will mention this directly in the commit as suggested elsewhere.

**Comment by clauswilke** [comment]
Thanks for pointing this out!

To be on the safe side, the copyright assignment should be in the git commit, so it's retained in the git history. I'll fix the labels on my end.

**Comment by malcolmbarrett** [comment]
Sure thing. I'll be more mindful of that if I see anything else.

**Comment by clauswilke** [comment]
Fixed now.

**Pull request closed without merging**
